[project]
name = "ssrn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.3.0",
    "dash-holoniq-wordcloud>=0.0.4",
    "pandas>=2.3.3",
]
